### PR TITLE
Add open-sourcey icons

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
@astanush Here are some new iconz

### CODE REVIEW

**Comment by fluxsauce** [comment]
`linux` should be `tux` IMHO; can you find one with color?

stallman and torvalds should be transparent

**Comment by patrickocoffeyo** [comment]
@fluxsauce donzies

**Comment by patrickocoffeyo** [comment]
selfie-0

**Comment by fluxsauce** [comment]
What about http://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png ?

**Comment by patrickocoffeyo** [comment]
@fluxsauce done! Had to smooth 'im out a bit

**Comment by fluxsauce** [comment]
selfie-0

**Comment by astanush** [comment]
Be sure to update the README too, so I know what shortcuts to set.

**Pull request merged**
