### PR TITLE
(archer) floating head

### PR DESCRIPTION
**Pull request by klamping**
Ran across this on the internet and had to have it.

### CODE REVIEW

**Comment by fluxsauce** [comment]
Do you want ants? Because this is how you get ants.

**Comment by patrickocoffeyo** [comment]
(jazzhands) is 100% mandatory.

**Comment by klamping** [comment]
@patrickocoffeyo shouldn't that be animated and <120px

https://s3.amazonaws.com/uploads.hipchat.com/60041/412898/zBcX5k4zfKcr5Sj/tumblr_mmd3t6qSIi1r75uoto1_500.gif for the animated part

**Comment by patrickocoffeyo** [comment]
The gif for this doesn't really work because it needs to be square, and with the extended robot arms, it it's very.... rectangular. If someone haz the image magix needed to make it work, go for it!

**Comment by patrickocoffeyo** [comment]
:shipit: ?

**Comment by astanush** [comment]
We use Slack now. Whatever.

**Pull request merged**
